name: rag_project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - faiss-cpu=1.7.4
  - flask=3.0.2
  - scikit-learn=1.4.0
  - numpy=1.26.4
  - pip:
      - sentence-transformers==2.2.2
      - langchain-nvidia-ai-endpoints==0.0.4
      - requests==2.31.0
      - bcrypt==4.1.2
      - flask-cors==4.0.0
      - sentencepiece==0.2.0
      - protobuf==4.25.3
