name: rag_project_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - faiss-cpu
  - flask
  - pip:
      - sentence-transformers
      - langchain_nvidia_ai_endpoints
      - scikit-learn
      - langchain-nvidia-ai-endpoints
      - python-dateutil
      - requests
      - pymongo
      - bcrypt
      - numpy
      - flask-cors
